# == Classic ==
classic: false

# == Blocks ==
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

color:
  when: always
  LS_COLORS: "di=31:ln=36:so=35:pi=33:ex=32:bd=34:cd=34:su=37:sg=30:tw=30:ow=34"
  custom:
    user: "red bold"
    directory: "red bold"
    symlink: "cyan italic"
    executable: "green bold"
    socket: "magenta bold"
    pipe: "yellow italic"
    device: "blue bold"
    special: "white bold"
    image: "yellow bold"
    video: "magenta bold"
    music: "green bold"
    archive: "red bold"
    document: "blue bold"
    readme: "green bold"

# == Date ==
date: date

# == Dereference ==
dereference: false

# == Icons ==
icons:
  when: auto
  theme: fancy
  separator: " "

# == Layout ==
layout: grid

# == Recursion ==
recursion:
  enabled: false

# == Size ==
size: default

# == Sorting ==
sorting:
  column: name
  reverse: false
  dir-grouping: none

# == No Symlink ==
no-symlink: false

# == Total size ==
total-size: false

# == Hyperlink ==
hyperlink: never

# == Symlink arrow ==
symlink-arrow: ⇒

# == Header ==
header: false

# == Literal ==
literal: false

# == Truncate owner ==
truncate-owner:
  after:
  marker: ""

